### PR TITLE
Add option to skip overwriting metadata profiles

### PR DESCRIPTION
**Pull request by richplant**
Added the option to skip pushing the default settings for Standard metadata profile in the AutoConfig script in case the user wants to manual configuration to persist through restarts.

### CODE REVIEW

**Comment by RandomNinjaAtk** [comment]
Why not jus turn off the script? Instead of an option to only disable one piece of it.

**Comment by richplant** [comment]
Because I want to use the other parts of it, like the naming conventions,
without having to monitor singles.

**Comment by RandomNinjaAtk** [comment]
But after the script runs the first time, you can just disable it and make any changes you want. Unless you always want it to run every time and overwrite the other settings. If we’re going to implement your method, it would probably be better to have each section as a setting to enable/disable to make it consistent.

**Comment by richplant** [comment]
Fair enough, I'd be in favour of making every section configurable.

**Comment by RandomNinjaAtk** [comment]
Resolved by: 
https://github.com/RandomNinjaAtk/arr-scripts/commit/faff19cbe8fe12e14802852f9db1c8232186df97
https://github.com/RandomNinjaAtk/arr-scripts/commit/3821ae75174f8606995f81c7c830f489e2fe6009

**Pull request closed without merging**
