### PR TITLE
YouTube fallback

### PR DESCRIPTION
**Pull request by jasperaelvoet**
PR for #58 
Can you test it and let me know what you think about it?
ATM it just does downloading, tagging, and importing. I have not yet tested if it retries via deezer/tidal after the not found period.

### CODE REVIEW

**Comment by jasperaelvoet** [comment]
It works really great now, just have to make sure it it keeps track of the YouTube downloads, and keeps the album marked as missing even after importing to lidarr.

**Comment by jasperaelvoet** [comment]
This PR was not really ready to merge yet. Like I said in my previous message there are still things to do. I suggest reverting the PR or you can wait until I open a new one with a fully stable and tested implementation of this feature.

**Comment by jasperaelvoet** [comment]
Just to give you an update, it'll probably take me a few weeks to finish this. Busy with other stuff...

**Comment by Peantz** [comment]
Hi,

did you find time to test this? really interested. Or should we use as alternative https://github.com/TheWicklowWolf/LidaTube ?

**Comment by b1ggi** [comment]
Hi,

did you find time to test this? really interested. Or should we use as alternative https://github.com/TheWicklowWolf/LidaTube ?

**Pull request merged**
