### PR TITLE
Updated QueueCleaner

### PR DESCRIPTION
**Pull request by baxterblk**
Added functions to remove stalled downloads from torrent client

### CODE REVIEW

**Comment by baxterblk** [comment]
@RandomNinjaAtk Please review

**Comment by RandomNinjaAtk** [comment]
I updated the script to account for "stalled" items. Please give the update I just pushed a try to see if it now handles your request.

**Comment by RandomNinjaAtk** [comment]
If you confirm the latest changes resolves this PR, please let me know. I appreciate that you took the time to refactor/rewrite it but you removed some of the functionality and and what was needed to handle your request was only a couple of additional lines, so the rewrite wasn't needed.

I also resolved port constraint issues and did some minor refactoring at the same time.

**Comment by baxterblk** [comment]
That works for me! Thank you.

**Comment by RandomNinjaAtk** [comment]
Resolved

**Pull request closed without merging**
